baseURL = "https://chrs.dev"
theme = "hugo-bearcub"
copyright = "Christian Mutti (CC BY 4.0)"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[languages]
  [languages.en]
    title = "chrs.dev"
    languageName = "en-US"
    LanguageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params]
  description = "Ocasianal ramblings of a Software Engineer"
  favicon = "favicon.png"

  images = []

  title = "chrs.dev"
  dateFormat = "2006-01-02"
  hideUntranslated = false
  themeStyle = "herman"
  generateSocialCard = true

  [params.social]

  [params.author]
    name = "Christian Mutti"
    email = "christian@chrs.dev" # Added to the footer so readers can reply to posts
